--角色用户表
CREATE TABLE [dbo].[SYS_USER_ROLE](
	[ROLE_ID] [varchar](32) NOT NULL,
	[USER_ID] [varchar](32) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'system', N'cr')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'xhy', N'wlc')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhuhj')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'wangxu')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'yanfengcen')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'yangqc')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'yangdongjie')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'system', N'yb')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'lizezhou')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'wangzh')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'liyan')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'chaijianhui')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'liush')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'gaojinding')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'fansx')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'wangbh')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'jingjs')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhangshaofa')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'yaoyong')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'huohs')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'majunhong')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhaoyuan')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhuwenming')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'yingjunliang')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'wangshudeng')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'caodaokui')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'xunzhe')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'sunpeng')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'kuaijinpeng')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'heshan')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhengmj')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'hushanjing')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'liweidong')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhangmt')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhangliang')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'liujian')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhangsq')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'wangwenbo')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'lukexin')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'lixianjun')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'laishouyi')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'biqingbo')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhangwei')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'maqifeng')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'liucr')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'wangcunhong')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'yangy')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'liuqf')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'duxinfu')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'haozhimin')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'zhangfz')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'quyuping')
INSERT [dbo].[SYS_USER_ROLE] ([ROLE_ID], [USER_ID]) VALUES (N'county', N'lixiaopo')