/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-02-11 05:44:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.busine;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class busine_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/base/include_BaseCommon.jsp", out, false);
      out.write("\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/common/css/commonView.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/busine/css/busine.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/public.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/busine/css/flowChart.css\" rel=\"stylesheet\">\r\n");
      out.write("<link  href=\"http://cache.amap.com/lbs/static/main1119.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link  href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrapStyle.css\"  rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://webapi.amap.com/maps?v=1.4.0&plugin=AMap.Geolocation,AMap.Geocoder&key=832085f1e357efae7eb7e34449ac1a36\"></script>\r\n");
      out.write("<script src=\"http://webapi.amap.com/ui/1.0/main.js?v=1.0.11\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/busine/busine.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/busine/ztreeBusine.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script  src=\"");
      out.print(request.getContextPath());
      out.write("/module/js/jquery.ztree.core.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/module/js/jquery.ztree.excheck.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/common/js/contentPath/db.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \tvar WEB_ROOT = \"");
      out.print(request.getContextPath() );
      out.write("\";\r\n");
      out.write(" \tvar userId=\"");
      out.print(session.getAttribute("userId"));
      out.write("\";\r\n");
      out.write(" \tvar state=\"");
      out.print(request.getParameter("state"));
      out.write("\";\r\n");
      out.write(" \tvar userjob=\"");
      out.print(session.getAttribute("userjob"));
      out.write("\";\r\n");
      out.write(" \tvar path = \"");
      out.print(request.getScheme() + "://"+ request.getServerName() + ":" + request.getServerPort());
      out.write("\";\r\n");
      out.write(" \tvar paramTp = \"");
      out.print(request.getParameter("tp"));
      out.write("\";\r\n");
      out.write(" \tvar busineId=\"");
      out.print(request.getParameter("busineId"));
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"headerDiv\" id=\"headerDiv\" style=\"height:40px;\">\r\n");
      out.write("\t<div class=\"header-content\">\r\n");
      out.write("\t\t<h2 class=\"paramTp1\">\r\n");
      out.write("\t\t\t<i class=\"fa icon-th-large\"></i>\r\n");
      out.write("\t\t\t<c><a style=\"text-decoration: none;color:#000;\" href=\"");
      out.print(request.getContextPath());
      out.write("/busine/busine.jsp\">业务受理</a></c>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h2 class=\"paramTp2\">\r\n");
      out.write("\t\t\t<i class=\"fa icon-th-large\"></i>\r\n");
      out.write("\t\t\t  <c>\r\n");
      out.write("\t\t\t\t<a style=\"text-decoration: none;\" href=\"javascript:history.back(-1)\">工作台</a>\r\n");
      out.write("\t\t\t\t<span style=\"margin-left: 5px;margin-right: 5px;\">></span>\r\n");
      out.write("\t\t\t\t\t业务受理\r\n");
      out.write("\t\t\t </c>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t</div> \r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"height: 92%;overflow: hidden;\">\r\n");
      out.write("\t  <div class=\"count_left\" >\r\n");
      out.write("\t    <div class=\"circleDiv\" id=\"untreatedBusine\">\r\n");
      out.write("\t\t \t<div class=\"cicle\">\r\n");
      out.write("\t\t \t\t<img class=\"cicel_img_p\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/images/bussine/dbevent.png\"/>\r\n");
      out.write("\t\t \t\t<div class=\"superscript\"><span id=\"noCount\">0</span></div>\r\n");
      out.write("\t\t \t</div>\r\n");
      out.write("\t\t \t<div class=\"marginDIV\">待处理事件</div>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t<div class=\"circleDiv\" id=\"handledBusine\">\r\n");
      out.write("\t\t \t<div class=\"cicle\">\r\n");
      out.write("\t\t \t\t<img class=\"cicel_img_p\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/images/bussine/ybevent.png\"/>\r\n");
      out.write("\t\t \t\t<div class=\"superscript\"><span id=\"handleCount\">0</span></div>\r\n");
      out.write("\t\t \t</div>\r\n");
      out.write("\t\t \t<div class=\"marginDIV\">已处理事件</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("     </div>\r\n");
      out.write("\t <div class=\"tab_right\">\r\n");
      out.write("         \t<div class=\"form-inline\" style=\"margin-top:5px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-2.2\" style=\"display: inline;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t  <span class=\"input-group-addon\" >事件编号:</span>\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"text\" class=\"form-control\" id=\"busineId\"  placeholder=\"请输入事件编号\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-2.2\" style=\"display: inline; \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group-addon\">上报人:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"busineUNm\" type=\"text\" class=\"form-control\"  placeholder=\"请输入上报人\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-2.2\" style=\"display: inline;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group-addon\">事件来源:</div>\r\n");
      out.write("\t\t\t\t\t\t\t <select class=\"form-control\"  id=\"busineTypeO\" style=\"margin-right:10px;\">\r\n");
      out.write("\t\t\t\t\t\t         <option selected='selected'  value=''>------请选择  ------</option>\r\n");
      out.write("\t\t\t\t\t\t         <option value='hzxh'>河长巡河</option>\r\n");
      out.write("\t\t\t\t\t\t         <option value='gzjb'>公众举报</option>\r\n");
      out.write("\t\t\t\t\t\t         <option value='zfjg'>执法监管</option>\r\n");
      out.write("\t\t\t\t\t\t     </select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button id=\"queryBusine\" class=\"btn btn-primary\" style=\"background-color: #3699fe;border: 0px;margin-left:10px;\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-search \"></span>&nbsp;查&nbsp;询\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<button  id=\"refreshBusine\"   class=\"btn btn-primary\" type=\"button\" style=\"background-color:#EE82EE;border: 0px;\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-refresh\" ></span>&nbsp;刷&nbsp;新\r\n");
      out.write("\t\t\t\t</button> \t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"test1\">\t\r\n");
      out.write("\t\t\t  <table id=\"patrol_busine\"  style=\"text-overflow:ellipsis;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t             <th field=\"busineId\" width=\"25\" align=\"center\">事件编号</th>\r\n");
      out.write("\t\t\t\t             <th field=\"busineOrigin\" width=\"20\" align=\"center\" >来源</th>\r\n");
      out.write("\t\t\t\t             <th field=\"busineType\"  width=\"20\" align=\"center\">事件类型</th>\r\n");
      out.write("\t\t\t\t             <th field=\"busineUnm\"  width=\"20\" align=\"center\" formatter=\"busineEvent.formatUser\">上报人员</th>\r\n");
      out.write("\t\t\t\t             <th field=\"busineUid\"  width=\"20\" hidden=\"true\">上报人员id</th>\r\n");
      out.write("\t\t\t\t             <th field=\"createTm\"  width=\"30\" align=\"center\" formatter=\"busineEvent.formatDate\">上报时间</th>\r\n");
      out.write("\t\t\t\t             <th field=\"busineAddress\"  width=\"40\" align=\"center\">事件地点</th>\r\n");
      out.write("\t\t\t\t             <th field=\"busineStatusNm\"  width=\"10\" align=\"center\" formatter=\"busineEvent.formatBusineColor\">事件状态</th>\r\n");
      out.write("\t\t\t\t             <th field=\"busineStatus\"  width=\"10\" hidden=\"true\">状态</th>\r\n");
      out.write("\t\t\t\t             <th field=\"originId\"  width=\"10\" hidden=\"true\">状态</th>\r\n");
      out.write("\t\t\t\t             <th field=\"dept\"  width=\"10\" hidden=\"true\">状态</th>\r\n");
      out.write("\t\t\t\t             <th field=\"job\"  width=\"10\" hidden=\"true\">状态</th>\r\n");
      out.write("\t\t\t\t             <th field=\"lastHandleUserId\"  width=\"10\" hidden=\"true\">上次处理人id</th>\r\n");
      out.write("\t\t\t\t             <th field=\"status\"  width=\"20\" hidden=\"true\" hidden=\"true\">流程状态</th>\r\n");
      out.write("\t\t\t\t             <th field=\"repeat\" width=\"15\" align=\"center\"  formatter=\"busineEvent.formatBusineRepeat\">操作</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"deltal_rigth\">\r\n");
      out.write("\t\t<div style=\"float: left;width: 50%;height: 100%;border-right: 1px solid #DDD;\">\r\n");
      out.write("\t\t\t<div class=\"deltal_div_info\">事件详情</div>\r\n");
      out.write("\t\t\t<div id=\"container_div\">\r\n");
      out.write("\t\t\t  <div id=\"leftContent\" onclick=\"busineEvent.next()\">\r\n");
      out.write("\t\t\t  \t\t<img id=\"left_img\"  style='cursor:pointer;'>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t    <div id=\"rightContent\">\r\n");
      out.write("\t\t\t      \t <div class=\"deltal_content\">\r\n");
      out.write("\t\t\t         \t<span>事件编码：</span>\r\n");
      out.write("\t\t\t         \t<span id=\"busineId2\"></span>\r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("\t\t\t         <div class=\"deltal_content\">\r\n");
      out.write("\t\t\t         \t<span>事件来源：</span>\r\n");
      out.write("\t\t\t         \t<span id=\"busineOri2\"></span>\r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("\t\t\t     \t <div class=\"deltal_content\">\r\n");
      out.write("\t\t\t         \t<span>事件类型：</span>\r\n");
      out.write("\t\t\t         \t<span id=\"busineTy2\"></span>\r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("\t\t\t     \t <div class=\"deltal_content\">\r\n");
      out.write("\t\t\t         \t<span>上报人员：</span>\r\n");
      out.write("\t\t\t         \t<span id=\"busineUN2\"></span>\r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("\t\t\t     \t <div class=\"deltal_content\">\r\n");
      out.write("\t\t\t          \t<span>上报时间：</span>\r\n");
      out.write("\t\t\t         \t<span id=\"createT2\"></span>\r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("\t\t\t     \t <div class=\"deltal_content\">\r\n");
      out.write("\t\t\t          \t<span>上报地点：</span>\r\n");
      out.write("\t\t\t         \t<span id=\"busineAddress2\"></span>\r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("\t\t\t     \t <div class=\"deltal_content\">\r\n");
      out.write("\t\t\t          \t<span>事件描述：</span>\r\n");
      out.write("\t\t\t       \t    <span id=\"busineDesc2\"></span> \r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div style=\"float: left;width: 50%;height: 100%;\">\r\n");
      out.write("\t\t\t<div class=\"work_div_info\">事件流程</div>\r\n");
      out.write("\t\t\t<div id=\"timeAxis\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade\" id=\"busineModel\"  tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\"  style=\"overflow-y: hidden;\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\" style=\"width:750px;\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\" style=\"padding:10px;background-color: #009f95;color: #fff;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\" style=\"font-size: 32px;margin-right: 10px;\">×</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">审核</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t  <div class=\"container-fluid\">\r\n");
      out.write("\t\t\t    <div class=\"row\">\r\n");
      out.write("\t\t\t      <div class=\"col-md-6\">\r\n");
      out.write("\t\t\t        <input type=\"hidden\" value=\"\" id=\"busineUid\">\r\n");
      out.write("\t\t\t         <input type=\"hidden\" value=\"\" id=\"busineOrgin\">\r\n");
      out.write("\t\t\t         <input type=\"hidden\" value=\"\" id=\"orginId\">\r\n");
      out.write("\t\t\t         <input type=\"hidden\" value=\"\" id=\"status\">\r\n");
      out.write("\t\t\t         <input type=\"hidden\" value=\"\" id=\"busineStatus\">\r\n");
      out.write("\t\t\t         <input type=\"hidden\" value=\"\" id=\"handleUserIdOne\">\r\n");
      out.write("\t\t\t     \t <table class=\"modal_tab\" style=\"font-size: 14px;color: #000;\">\r\n");
      out.write("\t\t\t     \t \t<tr>\r\n");
      out.write("\t\t\t     \t \t\t<td>事件编码：</td>\r\n");
      out.write("\t\t\t     \t \t\t<td><p id=\"busineIdS\" style=\"width:100px;\"></p></td>\r\n");
      out.write("\t\t\t     \t \t</tr>\r\n");
      out.write("\t\t\t     \t \t<tr>\r\n");
      out.write("\t\t\t     \t \t\t<td>事件来源：</td>\r\n");
      out.write("\t\t\t     \t \t\t<td><p id=\"busineOri\"></p></td>\r\n");
      out.write("\t\t\t     \t \t</tr>\r\n");
      out.write("\t\t\t     \t \t<tr>\r\n");
      out.write("\t\t\t     \t \t\t<td>事件类型：</td>\r\n");
      out.write("\t\t\t     \t \t\t<td ><p id=\"busineTypeS\"></p></td>\r\n");
      out.write("\t\t\t     \t \t</tr>\r\n");
      out.write("\t\t\t     \t \t<tr>\r\n");
      out.write("\t\t\t     \t \t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;报告人：</td>\r\n");
      out.write("\t\t\t     \t \t\t<td><p id=\"busineUN\"></p></td>\r\n");
      out.write("\t\t\t     \t \t</tr>\r\n");
      out.write("\t\t\t     \t \t<tr>\r\n");
      out.write("\t\t\t     \t \t\t<td>上报时间：</td>\r\n");
      out.write("\t\t\t     \t \t\t<td><p id=\"createT\"></p></td>\r\n");
      out.write("\t\t\t     \t \t</tr>\r\n");
      out.write("\t\t\t     \t \t<tr>\r\n");
      out.write("\t\t\t     \t \t\t<td>事件地点：</td>\r\n");
      out.write("\t\t\t     \t \t\t<td><p id=\"busineAddress\"></p></td>\r\n");
      out.write("\t\t\t     \t \t</tr>\r\n");
      out.write("\t\t\t     \t \t<tr>\r\n");
      out.write("\t\t\t     \t \t\t<td>事件描述：</td>\r\n");
      out.write("\t\t\t     \t \t\t<td><p id=\"busineDesc\"></p></td>\r\n");
      out.write("\t\t\t     \t \t</tr>\r\n");
      out.write("\t\t\t     \t \t<tr>\r\n");
      out.write("\t\t\t     \t \t\t<td>上报图片：</td>\r\n");
      out.write("\t\t\t     \t \t\t<td><p id=\"url\"></p></td>\r\n");
      out.write("\t\t\t     \t \t</tr>\r\n");
      out.write("\t\t\t     \t \t");
      out.write("\r\n");
      out.write("\t\t\t     \t \t<tr id=\"view\">\r\n");
      out.write("\t\t\t     \t \t\t<td>处理意见：</td>\r\n");
      out.write("\t\t\t     \t \t\t<td><textarea rows=\"3\" cols=\"30\" id=\"handleView\"></textarea></td>\r\n");
      out.write("\t\t\t     \t \t</tr>\r\n");
      out.write("\t\t\t     \t \t\r\n");
      out.write("\t\t\t     \t </table>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t      <div class=\"col-md-6\" style=\"width:330px;heigth:100px;margin-left:55%;border: 2px solid #eee; \" id=\"container\">\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t      \r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"modal-footer\" id=\"foot\">\r\n");
      out.write("\t\t\t\t<button  class=\"btn btn-default btns\" id=\"checkBusine\" type=\"button\">\r\n");
      out.write("\t\t\t\t    &nbsp;处&nbsp;理\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-default btns\" id=\"deliverBusine\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t&nbsp;转&nbsp;交\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<button  class=\"btn btn-default btns\" id=\"invalidBusine\" type=\"button\">\r\n");
      out.write("\t\t\t\t    &nbsp;无&nbsp;效\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<!-- <button class=\"btn btn-default btns\" id=\"returnBusine\"  type=\"button\">\r\n");
      out.write("\t\t\t\t\t&nbsp;退&nbsp;回\r\n");
      out.write("\t\t\t\t</button> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 转交选择人页面 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"busineUserModel\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" style=\"overflow-y: hidden;\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\" style=\"width:700px;height:auto;overflow-y: auto;overflow-x: hidden;\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\" style=\"padding:10px;background-color: #009f95;color: #fff;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\" style=\"font-size: 32px;margin-right: 10px;\">×</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">转交人员</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\" style=\"height:450px;\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t    <span  class='titlespan'>石城县成员单位</span>\r\n");
      out.write("\t\t\t\t    <span  class='titlespan' style=\"padding-left:340px;\">处理人员</span>\r\n");
      out.write("\t\t\t\t</div>    \r\n");
      out.write("\t\t\t\t<div class=\"col-xs-5\" style=\"margin-top:10px;border: 1px solid #000;padding-right:0px;height:400px;\">\r\n");
      out.write("\t\t\t        <ul id=\"busineZtree\"  class=\"ztree\" style=\"margin-top:0;overflow: auto;height:400px\">\r\n");
      out.write("\t\t\t        </ul>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div  class=\"col-xs-1\"  style=\"margin-top:200px;margin-right:15px;\"> \r\n");
      out.write("\t\t\t       <img src=\"");
      out.print(request.getContextPath());
      out.write("/common/images/bussine/addicon.jpg\" style=\"width:45px;height:45px;\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"col-xs-5\" style=\"margin-top:10px;border: 1px solid #000;padding-right:0px;height:400px;\">\r\n");
      out.write("\t\t\t       <input  id=\"resultUser\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t       <ul class=\"ztree\" style=\"margin-top:0;overflow: auto;height:400px;color:red;font-weight:bold;\" id=\"busineUserName\"> \r\n");
      out.write("\t\t\t       </ul>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\" id=\"foot\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-default btns\" id=\"retuBusine\" type=\"button\" style=\"color: #333;background-color: #fff;border-color: #adadad;\"  data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t&nbsp;关&nbsp;闭\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<button  class=\"btn btn-default btns\" id=\"conBusine\" type=\"button\">\r\n");
      out.write("\t\t\t\t    &nbsp;确&nbsp;定\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  <div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("if(parseInt(paramTp)){\r\n");
      out.write("\t$(\".paramTp1\").hide();\r\n");
      out.write("\t$(\".paramTp2\").show();\r\n");
      out.write("}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
