/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-02-11 01:01:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t");

		String appPath = request.getScheme() + "://"+ request.getServerName() + ":" + request.getServerPort();
		pageContext.setAttribute("appPath", appPath);
	    pageContext.setAttribute("basePath", request.getContextPath()+"/"); 
    
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" contents=\"width=device-width,initial-scale=1\">\r\n");
      out.write("    <title>石城县水质水量水环境监测平台</title>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("common/js/md5/md5.js\"></script>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/base/include_BootStrap.jsp", out, false);
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/base/include_Common.jsp", out, false);
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("module/js/login.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("module/login/css/login.css\" >\r\n");
      out.write("   \t<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("common/images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("common/images/favicon.ico type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"bookmark\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("common/images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \tvar WEB_ROOT = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    \tvar APP_ROOT = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; \r\n");
      out.write("    \t$(function(){\r\n");
      out.write("    \t\tif (top != window){    \t\t\t\r\n");
      out.write("   \t\t      top.location.href = window.location.href;    \r\n");
      out.write("    \t\t} \r\n");
      out.write("    \t\tvar h = window.screen.height; \r\n");
      out.write("    \t\tvar i = 7;\r\n");
      out.write("    \t\tif(h < 900){\r\n");
      out.write("    \t\t\ti = 11;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t$(\"#login_img\").css(\"margin\",\"\"+h/i+\"px auto\");\r\n");
      out.write("    \t\t$(\".weixin\").css(\"top\",h/3);\r\n");
      out.write("    \t\t$(\".hzzapp\").css(\"top\",h/3+10);\r\n");
      out.write("    \t});\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div  class=\"loginDiv\" ></div>\r\n");
      out.write("\t<div class=\"div-ul\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<label class=\"li_tab\">河长制信息管理系统登录</label>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<label class=\"login_lab lab_pas\">账&nbsp;&nbsp;号：</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"UserName\" class=\"form-control titl login_ipt\" placeholder=\"用户名或手机号\" >\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<label  class=\"login_lab lab_pas\">密&nbsp;&nbsp;码：</label>\r\n");
      out.write("\t\t\t\t<input type=\"password\" id=\"Password\" class=\"form-control titl login_ipt\" placeholder=\"请输入密码\"  >\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<label class=\"login_lab lab_yz\">验证码：</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"verifyCode\" class=\"form-control titl login_ipt\" placeholder=\"请输入验证码\">\r\n");
      out.write("\t\t\t\t<p style=\"margin: 10px 0 0 88px;\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("base/api/login/getVerifyCodeImage\" id=\"verifyCodeImage\">\r\n");
      out.write("\t\t\t\t\t<a class=\"pass-change-verifyCode\" href=\"javascript:void(0)\" onclick=\"loginInfo.reloadVerifyCode()\" >换一张</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"登&nbsp;&nbsp;&nbsp;&nbsp;录\"  class=\"btn btn-primary btn-login\" onclick=\"loginInfo.login();\" >\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"logo_bj_div\"></div>\r\n");
      out.write("\t<div class=\"weixin\" onmouseover=\"this.className = 'weixin on';\" onmouseout=\"this.className = 'weixin';\">\r\n");
      out.write("\t\t<a href=\"javascript:;\"></a>\r\n");
      out.write("\t    <div class=\"weixin_nr\">\r\n");
      out.write("\t    \t<div class=\"arrow\"></div>\r\n");
      out.write("\t    \t<p class=\"logo-ewm\">扫描二维码</p>\r\n");
      out.write("\t        <p class=\"logo-gz\">关注河长制公众号</p>\r\n");
      out.write("\t        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("module/login/images/hzz-wechat.jpg\" style=\"width:150px; height:150px; \"/>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"hzzapp\" onmouseover=\"this.className = 'hzzapp on';\" onmouseout=\"this.className = 'hzzapp';\">\r\n");
      out.write("\t\t<a href=\"javascript:;\"></a>\r\n");
      out.write("\t    <div class=\"hzzapp_nr\">\r\n");
      out.write("\t    \t<div class=\"arrow\"></div>\r\n");
      out.write("\t    \t<p class=\"logo-ewm\">扫描二维码</p>\r\n");
      out.write("\t        <p class=\"logo-gz\">下载Android河长版</p>\r\n");
      out.write("\t        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("module/login/images/hzz-app.jpg\" style=\"width:150px; height:150px;\"/>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tab-gxhy\">\r\n");
      out.write("\t\t<span id=\"tb-zoom\" class=\"tab-gxhy-g gx\"></span>\r\n");
      out.write("\t\t<span id=\"lgt\" class=\"tab-gxhy-g gx\" ></span>\r\n");
      out.write("\t\t<div class=\"tab-gxhy-v\">\r\n");
      out.write("\t\t\t<span class=\"tab-gxhy-g\">技术支持：北京国信华源科技有限公司   <a href=\"http://www.bjgxhy.com\" target=\"blank\" style=\"color: #fff;text-decoration: none;\">www.bjgxhy.com</a>&nbsp;&nbsp;|&nbsp;&nbsp; 服务热线：4008-762-395</span> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
