/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-03-05 07:37:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.basicSite;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class basicSiteInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/base/include_BaseCommon.jsp", out, false);
      out.write("\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/common/css/commonView.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/basicSite/css/basicSite.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/basicSite/basicSite.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \tvar WEB_ROOT = \"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write(" \tvar paramStcd = \"");
      out.print(request.getParameter("stcd"));
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"headerDiv\" id=\"headerSitediv\">\r\n");
      out.write("\t<div class=\"header-content\">\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<i class=\"fa icon-th-large\"></i>\r\n");
      out.write("\t\t\t<c>测站基础信息</c>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t<div style=\"background-color: #FFFFFF;\"class=\"\" >\r\n");
      out.write("\t\t<div class=\"form-inline\" method=\"post\" id=\"form_data_info\">\r\n");
      out.write("\t\t\t<div id=\"siteDiv\" style=\"padding: 10px;border-bottom: 1px solid #dddddd;\">\r\n");
      out.write("\t\t\t\t<button  onclick=\"site.QuerySttp('');\" type=\"button\"  class='btnSite current'>全部</button> \r\n");
      out.write("\t\t\t\t<button  onclick=\"site.QuerySttp('PP');\" type=\"button\"  class='btnSite'>雨量站</button> \r\n");
      out.write("\t\t\t\t<button  onclick=\"site.QuerySttp('ZZ');\" type=\"button\"  class='btnSite'>河道水位站</button> \r\n");
      out.write("\t\t\t\t<button  onclick=\"site.QuerySttp('SP');\" type=\"button\"  class='btnSite'>视频站</button> \r\n");
      out.write("\t\t\t\t<button  onclick=\"site.QuerySttp('SZ');\" type=\"button\"  class='btnSite'>水质站</button> \r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2.5\" style=\"display: inline;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t  <span class=\"input-group-addon\" >测站信息:</span>\r\n");
      out.write("\t\t\t\t\t  <input type=\"text\" class=\"form-control\" id=\"stcdkey\"  placeholder=\"请输入编码或名称\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button id=\"queryBasic\" class=\"btn btn-primary\" style=\"background-color: #0ab1f8;border: 0px;\" type=\"button\" >\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-search \" ></span>&nbsp;查&nbsp;询\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("<!-- \t\t\t\t<button id=\"saveSite\" class=\"btn btn-primary\" style=\"background-color: #0ab1f8;border: 0px;\" type=\"button\" >\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-plus \" ></span>&nbsp;添&nbsp;加\r\n");
      out.write("\t\t\t\t</button> -->\r\n");
      out.write("<!-- \t\t\t\t<button  id=\"refreshBasic\"   class=\"btn btn-primary\" type=\"button\" style=\"background-color:#EE82EE;border: 0px;\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-refresh\" ></span>&nbsp;刷&nbsp;新\r\n");
      out.write("\t\t\t\t</button> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <table id=\"patrol_catalogSite\"  style=\"text-overflow:ellipsis;\">\r\n");
      out.write("   <thead>\r\n");
      out.write("\t <tr>\r\n");
      out.write("            <th field=\"stcd\"  width=\"30\" align=\"center\">测站编码</th>\r\n");
      out.write("            <th field=\"stnm\" width=\"40\" align=\"center\">测站名称</th>\r\n");
      out.write("            <th field=\"rvnm\" width=\"40\" align=\"center\" >所属河流</th>\r\n");
      out.write("            <th field=\"hnnm\"  width=\"40\" align=\"center\">所属水系</th>\r\n");
      out.write("            <th field=\"lgtd\" width=\"40\" align=\"center\">经度</th>\r\n");
      out.write("            <th field=\"lttd\" width=\"40\" align=\"center\">纬度</th>\r\n");
      out.write("            <th field=\"stlc\" width=\"40\" align=\"left\" halign=\"center\">站址</th>\r\n");
      out.write("            <th field=\"addvcd\" width=\"40\" align=\"center\">行政区划码</th>\r\n");
      out.write("            <th field=\"sttpNm\" width=\"40\" align=\"center\">站类</th>\r\n");
      out.write("            <th field=\"basicSite\" width=\"40\"    align=\"center\"  formatter=\"site.formatSiteRepeat\">操作</th>\r\n");
      out.write("\t </tr>\r\n");
      out.write("   </thead>\r\n");
      out.write("  </table>\r\n");
      out.write("  <!-- 基础测站详情 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"SiteDetail\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\"  style=\"overflow-y: hidden;\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\" style=\"height: 570px;width:550px;overflow-y: auto;overflow-x: hidden;\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\"  style=\"padding:10px;background-color: #009f95;color: #fff;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\" style=\"font-size: 32px;margin-right: 10px;\">×</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">基本信息</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t  <table class=\"siteTable\">\r\n");
      out.write("\t\t\t       <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">测站编码：</td>\r\n");
      out.write("\t\t\t           <td  id=\"stcd_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">测站名称：</td>\r\n");
      out.write("\t\t\t           <td id=\"stnm_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t       </tr>\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">河流名称：</td>\r\n");
      out.write("\t\t\t           <td id=\"rvnm_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">水系名称：</td>\r\n");
      out.write("\t\t\t           <td id=\"hnnm_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t       </tr>\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">流域名称：</td>\r\n");
      out.write("\t\t\t           <td  id=\"bsnm_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">经度：</td>\r\n");
      out.write("\t\t\t           <td id=\"lgtd_detail\"  class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t       </tr>\r\n");
      out.write("\t\t\t       <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">纬度：</td>\r\n");
      out.write("\t\t\t           <td  id=\"lttd_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">站址：</td>\r\n");
      out.write("\t\t\t           <td id=\"stlc_detail\"  class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t       </tr>\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">站类：</td>\r\n");
      out.write("\t\t\t           <td id=\"sttp_detail\"   class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">行政区：</td>\r\n");
      out.write("\t\t\t           <td id=\"addvcd_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">基面名称：</td>\r\n");
      out.write("\t\t\t           <td   id=\"dtmnm_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">基面高程：</td>\r\n");
      out.write("\t\t\t           <td id=\"dtmel_detail\"   class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t        </tr>  \r\n");
      out.write("\t\t\t         <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">基面修正值：</td>\r\n");
      out.write("\t\t\t           <td   id=\"mdpr_detail\"  class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">报汛等级：</td>\r\n");
      out.write("\t\t\t           <td id=\"frgrd_detail\"   class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">建站年月：</td>\r\n");
      out.write("\t\t\t           <td  id=\"edfrym_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">始报年月：</td>\r\n");
      out.write("\t\t\t           <td  id=\"bgfrym_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t         <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">隶属行业单位：</td>\r\n");
      out.write("\t\t\t           <td  id=\"atcunit_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">信息管理单位：</td>\r\n");
      out.write("\t\t\t           <td  id=\"admauth_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t         <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">交换管理单位：</td>\r\n");
      out.write("\t\t\t           <td  id=\"locality_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">测站岸别：</td>\r\n");
      out.write("\t\t\t           <td  id=\"stbk_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t         <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">测站方位：</td>\r\n");
      out.write("\t\t\t           <td id=\"stazt_detail\"   class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">至河口距离：</td>\r\n");
      out.write("\t\t\t           <td  id=\"dstrvm_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t         </tr>\r\n");
      out.write("\t\t\t          <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">集水面积：</td>\r\n");
      out.write("\t\t\t           <td id=\"drna_detail\"  class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">拼音码：</td>\r\n");
      out.write("\t\t\t           <td  id=\"phcd_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t         </tr>\r\n");
      out.write("\t\t\t          <tr>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">启用标志：</td>\r\n");
      out.write("\t\t\t           <td id=\"usfl_detail\"      class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t           <td class=\"leftTr\">备注：</td>\r\n");
      out.write("\t\t\t           <td  id=\"comments_detail\" class=\"rightTr\"></td>\r\n");
      out.write("\t\t\t         </tr>\r\n");
      out.write("\t\t\t  </table>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <!-- 模态框（Modal） -->\r\n");
      out.write("<div class=\"modal fade\" id=\"stModel\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\" style=\"overflow: auto;\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\" style=\"width:750px;height: auto;\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\" style=\"padding:10px;background-color: #009f95;color: #fff;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\" style=\"font-size: 32px;margin-right: 10px;\">×</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">测站基础信息</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\" id=\"modal-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" role=\"form\" id=\"form_data_st\">\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"firstname\" class=\"col-sm-3 control-label\">&nbsp;&nbsp;测站编码</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t      <input type=\"hidden\" class=\"form-control\" name=\"stcd\" id=\"stcd\" >\r\n");
      out.write("\t\t\t\t      <input type=\"text\" class=\"form-control\" name=\"stcd-t\" id=\"stcd-t\" disabled=\"disabled\" maxlength=\"15\">\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"lastname\" class=\"col-sm-3 control-label\"><span style=\"color: red;\">★</span>&nbsp;&nbsp;测站名称</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t      <input type=\"text\" class=\"form-control\" name=\"stnm\" id=\"stnm\" maxlength=\"10\">\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"lastname\" class=\"col-sm-3 control-label\"><span style=\"color: red;\">★</span>所属水系</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t      <input type=\"text\" class=\"form-control\" name=\"hnnm\" id=\"hnnm\" >\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"lastname\" class=\"col-sm-3 control-label\"><span style=\"color: red;\">★</span>所属河流</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t      <input type=\"text\" class=\"form-control\" name=\"rvnm\" id=\"rvnm\" >\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"lastname\" class=\"col-sm-3 control-label\"><span style=\"color: red;\">★</span>&nbsp;&nbsp;经度</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t      <input type=\"text\" class=\"form-control\" name=\"lgtd\" id=\"lgtd\" placeholder=\"请输入经度,格式：116.526726\" maxlength=\"10\"  onblur=\"check(this)\"  onkeyup=\"this.value=this.value.replace(/[^0-9.]/g,'')\" > \r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"lastname\" class=\"col-sm-3 control-label\"><span style=\"color: red;\">★</span>&nbsp;&nbsp;纬度</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t      <input type=\"text\" class=\"form-control\" name=\"lttd\" id=\"lttd\" placeholder=\"请输入纬度,格式：40.007181\" maxlength=\"10\" onblur=\"check(this)\"  onkeyup=\"this.value=this.value.replace(/[^0-9.]/g,'')\" >\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"lastname\" class=\"col-sm-3 control-label\"><span style=\"color: red;\">★</span>&nbsp;&nbsp;站址</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t      <input type=\"text\" class=\"form-control\" name=\"stlc\"  id=\"stlc\" >\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"lastname\" class=\"col-sm-3 control-label\"><span style=\"color: red;\">★</span>&nbsp;&nbsp;站类</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t          <select class=\"form-control length-input\"  id=\"sttp\" name=\"sttp\" >\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"\" disabled=\"disabled\">请选择</option>\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"PP\">雨量站</option>\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"MM\">气象站</option>\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"BB\">蒸发站</option>\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"ZQ\">河道水文站</option>\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"RR\">水库水位站</option>\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"DD\">堰闸水文站</option>\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"ZZ\">河道水位站</option>\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"TT\">潮位站</option>\r\n");
      out.write("\t\t\t\t\t\t      \t<option value=\"RR\">水库水文站</option>\r\n");
      out.write("\t\t\t\t\t\t        <option value=\"DP\">泵站</option>\r\n");
      out.write("\t\t\t\t\t\t        <option value=\"ZG\">地下水站</option>\r\n");
      out.write("\t\t\t\t\t\t        <option value=\"SS\">墒情站</option>\r\n");
      out.write("\t\t\t\t\t\t        <option value=\"ZB\">分洪水位站</option>\r\n");
      out.write("\t\t\t\t\t\t        <option value=\"SP\">视频站</option>\r\n");
      out.write("\t\t\t\t\t\t        <option value=\"SY\">水源地</option>\r\n");
      out.write("\t\t\t\t\t\t        <option value=\"PW\">排污口</option>\r\n");
      out.write("\t\t\t\t\t   \t  </select>    \t  \r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"lastname\" class=\"col-sm-3 control-label\">行政区划码</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t      <input type=\"text\" class=\"form-control\" name=\"addvcd\" id=\"addvcd\" maxlength=\"11\" onkeyup=\"this.value=this.value.replace(/\\D/g,'')\">\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-default\" type=\"button\" data-dismiss=\"modal\"  style=\"color: #333;background-color: #fff;border-color: #adadad;\">\r\n");
      out.write("\t\t\t\t\t&nbsp;关&nbsp;闭\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<button   class=\"btn btn-default\" style=\"background-color: #009f95;color: #fff;\" id=\"updateSt\"  type=\"button\">\r\n");
      out.write("\t\t\t\t    &nbsp;修&nbsp;改\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
